[project]
name = "url-shortener"
version = "0.1.0"
description = "URL shortener"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest"
]

[tool.pytest.ini_options]
pythonpath = ["."]